name: ðŸ› Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: >
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: e.g., Mac OS, Chrome 123
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      placeholder: Paste logs or screenshots here
    validations:
      required: false
